name: Test Workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
env:
  ONE: ${{ secrets.GH_TOKEN }}
  TWO: ${{ secrets.PASSWORD }}
jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: First step
        run: |
          echo "First  environment variable is $ONE"
          if [ $TWO == "12345password" ]
          then
            echo "Matches"
          else
            echo "Does not match"
          fi
